@local = http://localhost:8080
@deployed = renderurl

// Set to "local" or "deployed" based on what you're testing.
@host = {{local}}

//*******************************************************************************
// Root
//*******************************************************************************
### Root
GET {{host}}/ HTTP/1.1

//*******************************************************************************
// Spells
//*******************************************************************************

### Get All Spells
GET {{host}}/spells HTTP/1.1

### Get Spell By Id
GET {{host}}/spells/653af14334871ac29de9fb37 HTTP/1.1

### Create Spell
POST {{host}}/spells HTTP/1.1
content-type: application/json
{
    "name": "Magic Missile",
    "description": "Pew pew!"
}

### Update Spell
POST {{host}}/spells/653af14334871ac29de9fb37 HTTP/1.1
content-type: application/json
{
    "description": "Pew pew PEW!"
}

### Delete Spell
POST {{host}}/spells HTTP/1.1

//*******************************************************************************
// MONSTERS
//*******************************************************************************

### Get All Monsters
GET {{host}}/monsters HTTP/1.1

### Get Monster By Id
GET {{host}}/monsters/653aefdf7e31c8e546fd97a9 HTTP/1.1 

### Create Monster
POST {{host}}/monsters HTTP/1.1
content-type: application/json

{
    "name": "Flumph",
    "str": 10,
    "dex": 12,
    "con": 8,
    "wis": 12,
    "int": 8,
    "cha": 10
}

### Update Monster
POST {{host}}/spells/653af14334871ac29de9fb37 HTTP/1.1
content-type: application/json
{
    "str": 18
}

### Delete Spell
POST {{host}}/spells HTTP/1.1


